#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely
# Sleep 2 in each iteration
# Display "I am invincible!!!" when receive a SIGTERM signal

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
